"""Markdown, JSON, and CSV run reports."""

from __future__ import annotations

import csv
import json
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.runner import ExecutedTest

log = logging.getLogger("nqs.reporting")


def write_reports(
    reports_dir: Path,
    run_id: str,
    executed: list[ExecutedTest],
    environment: dict[str, Any],
    load_errors: list[str],
    duration_sec: float,
) -> dict[str, Path]:
    reports_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    passed = sum(1 for t in executed if t.status == "passed")
    failed = sum(1 for t in executed if t.status == "failed")
    skipped = sum(1 for t in executed if t.status == "skipped")
    total = len(executed)

    payload: dict[str, Any] = {
        "run_id": run_id,
        "generated_at": ts,
        "duration_sec": round(duration_sec, 4),
        "summary": {
            "total": total,
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
        },
        "load_warnings": load_errors,
        "environment": environment,
        "tests": [_executed_to_dict(t) for t in executed],
    }

    json_path = reports_dir / f"nqs_report_{run_id}.json"
    md_path = reports_dir / f"nqs_report_{run_id}.md"
    csv_path = reports_dir / f"nqs_summary_{run_id}.csv"

    try:
        json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    except OSError as e:
        log.error("Failed to write JSON report: %s", e)
        raise

    try:
        md_path.write_text(_render_markdown(payload), encoding="utf-8")
    except OSError as e:
        log.error("Failed to write Markdown report: %s", e)
        raise

    try:
        _write_csv(csv_path, executed, run_id, duration_sec)
    except OSError as e:
        log.error("Failed to write CSV: %s", e)

    return {"json": json_path, "markdown": md_path, "csv": csv_path}


def _executed_to_dict(t: ExecutedTest) -> dict[str, Any]:
    d = asdict(t)
    return d


def _render_markdown(p: dict[str, Any]) -> str:
    s = p["summary"]
    lines = [
        "# Network Qualification Suite — Run Report",
        "",
        f"**Run ID:** `{p['run_id']}`  ",
        f"**Generated:** {p['generated_at']}  ",
        f"**Duration:** {p['duration_sec']:.2f}s",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total | {s['total']} |",
        f"| Passed | {s['passed']} |",
        f"| Failed | {s['failed']} |",
        f"| Skipped | {s['skipped']} |",
        "",
    ]
    if p.get("load_warnings"):
        lines += ["## Plan load warnings", ""]
        for w in p["load_warnings"]:
            lines.append(f"- {w}")
        lines.append("")

    lines += [
        "## Environment snapshot",
        "",
        "```json",
        json.dumps(p["environment"], indent=2),
        "```",
        "",
        "## Results",
        "",
        "| Test ID | Name | Protocol | Status | ms | Retries | Notes |",
        "|---------|------|----------|--------|-----|---------|-------|",
    ]
    for t in p["tests"]:
        note = (t.get("error_detail") or t.get("message") or "")[:120]
        lines.append(
            f"| `{t['test_id']}` | {t['name'][:40]} | {t['protocol']} | "
            f"**{t['status']}** | {t['duration_ms']:.1f} | {t['retries_used']} | {note} |"
        )

    lines += ["", "## Metrics (per test)", ""]
    for t in p["tests"]:
        lines.append(f"### `{t['test_id']}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(t.get("metrics", {}), indent=2))
        lines.append("```")
        lines.append("")

    lines += [
        "---",
        "",
        "*Generated by [network-qualification-suite](https://github.com/) — qualification-style validation run.*",
        "",
    ]
    return "\n".join(lines)


def _write_csv(
    path: Path,
    executed: list[ExecutedTest],
    run_id: str,
    duration_sec: float,
) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "run_id",
                "duration_sec",
                "test_id",
                "name",
                "protocol",
                "status",
                "duration_ms",
                "retries_used",
                "message",
            ]
        )
        for t in executed:
            w.writerow(
                [
                    run_id,
                    f"{duration_sec:.4f}",
                    t.test_id,
                    t.name,
                    t.protocol,
                    t.status,
                    t.duration_ms,
                    t.retries_used,
                    t.message,
                ]
            )
